// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjjnehfmnznpujtvbwln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqam5laGZtbnpucHVqdHZid2xuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3OTU5NDcsImV4cCI6MjA2NTM3MTk0N30.EmGBXAA5B5BmLVrY8uNhBuJpvR-4D34klzoa6G_BkH8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});